image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000

tasks:
  - init: yarn
    command: yarn --cwd browser-app start

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==